cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED API_DIR)
	get_filename_component(API_DIR "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
endif()
if(NOT DEFINED TORCH_DIR)
	set(TORCH_DIR "${API_DIR}/libtorch")
endif()

function(lock_value name output)
	file(STRINGS "${API_DIR}/versions.env" lines REGEX "^${name}=")
	list(LENGTH lines count)
	if(NOT count EQUAL 1)
		message(FATAL_ERROR "Dependency lock must define ${name} exactly once")
	endif()
	list(GET lines 0 line)
	string(REGEX REPLACE "^[^=]+=" "" value "${line}")
	set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(quoted_define path name expected)
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "Dependency file is missing: ${path}")
	endif()
	file(STRINGS "${path}" lines REGEX "^[ \t]*#define[ \t]+${name}[ \t]+\"")
	list(LENGTH lines count)
	if(NOT count EQUAL 1)
		message(FATAL_ERROR "Cannot read ${name} from ${path}")
	endif()
	list(GET lines 0 line)
	string(REGEX REPLACE ".*\"([^\"]+)\".*" "\\1" actual "${line}")
	if(NOT actual STREQUAL expected)
		message(FATAL_ERROR "${name} version mismatch: expected ${expected}, found ${actual}")
	endif()
endfunction()

function(integer_define path name expected)
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "Dependency file is missing: ${path}")
	endif()
	file(STRINGS "${path}" lines REGEX "^[ \t]*#define[ \t]+${name}[ \t]+[0-9]+")
	list(LENGTH lines count)
	if(NOT count EQUAL 1)
		message(FATAL_ERROR "Cannot read ${name} from ${path}")
	endif()
	list(GET lines 0 line)
	string(REGEX MATCH "[0-9]+" actual "${line}")
	if(NOT actual STREQUAL expected)
		message(FATAL_ERROR "${name} version mismatch: expected ${expected}, found ${actual}")
	endif()
endfunction()

lock_value(TORCH_VERSION locked_torch_version)
lock_value(TORCH_VARIANTS locked_torch_variants)
lock_value(HDF5_VERSION locked_hdf5_version)
lock_value(ZLIB_VERSION locked_zlib_version)
lock_value(JSON_VERSION locked_json_version)
lock_value(NINJA_VERSION locked_ninja_version)
lock_value(CHESS_SHA256 locked_chess_sha256)

set(torch_version_file "${TORCH_DIR}/build-version")
if(NOT EXISTS "${torch_version_file}")
	message(FATAL_ERROR "LibTorch build-version is missing: ${torch_version_file}")
endif()
file(STRINGS "${torch_version_file}" torch_build LIMIT_COUNT 1)
string(STRIP "${torch_build}" torch_build)
if(NOT torch_build MATCHES "^([^+]+)\\+(.+)$")
	message(FATAL_ERROR "Unrecognized LibTorch build-version: ${torch_build}")
endif()
set(actual_torch_version "${CMAKE_MATCH_1}")
set(actual_torch_variant "${CMAKE_MATCH_2}")
if(NOT actual_torch_version STREQUAL locked_torch_version)
	message(FATAL_ERROR
		"LibTorch version mismatch: expected ${locked_torch_version}, found ${actual_torch_version}")
endif()
string(REPLACE "," ";" allowed_torch_variants "${locked_torch_variants}")
list(FIND allowed_torch_variants "${actual_torch_variant}" variant_index)
if(variant_index EQUAL -1)
	message(FATAL_ERROR
		"Unsupported LibTorch variant ${actual_torch_variant}; allowed: ${locked_torch_variants}")
endif()
if(DEFINED EXPECTED_TORCH_VARIANT AND
	NOT actual_torch_variant STREQUAL EXPECTED_TORCH_VARIANT)
	message(FATAL_ERROR
		"LibTorch variant mismatch: expected ${EXPECTED_TORCH_VARIANT}, found ${actual_torch_variant}")
endif()

quoted_define("${API_DIR}/hdf5/include/H5pubconf.h" H5_VERSION "${locked_hdf5_version}")
quoted_define("${API_DIR}/zlib/include/zlib.h" ZLIB_VERSION "${locked_zlib_version}")

string(REPLACE "." ";" json_parts "${locked_json_version}")
list(LENGTH json_parts json_part_count)
if(NOT json_part_count EQUAL 3)
	message(FATAL_ERROR "Invalid JSON_VERSION in dependency lock: ${locked_json_version}")
endif()
list(GET json_parts 0 json_major)
list(GET json_parts 1 json_minor)
list(GET json_parts 2 json_patch)
set(json_header "${API_DIR}/nlohmann/include/nlohmann/json.hpp")
integer_define("${json_header}" NLOHMANN_JSON_VERSION_MAJOR "${json_major}")
integer_define("${json_header}" NLOHMANN_JSON_VERSION_MINOR "${json_minor}")
integer_define("${json_header}" NLOHMANN_JSON_VERSION_PATCH "${json_patch}")

set(chess_header "${API_DIR}/chess/chess.hpp")
if(NOT EXISTS "${chess_header}")
	message(FATAL_ERROR "chess-library header is missing: ${chess_header}")
endif()
file(SHA256 "${chess_header}" actual_chess_sha256)
if(NOT actual_chess_sha256 STREQUAL locked_chess_sha256)
	message(FATAL_ERROR
		"chess-library checksum mismatch: expected ${locked_chess_sha256}, found ${actual_chess_sha256}")
endif()

if(WIN32)
	set(ninja "${API_DIR}/ninja/ninja.exe")
else()
	set(ninja "${API_DIR}/ninja/ninja")
endif()
if(NOT EXISTS "${ninja}")
	message(FATAL_ERROR "Ninja is missing: ${ninja}")
endif()
execute_process(
	COMMAND "${ninja}" --version
	RESULT_VARIABLE ninja_status
	OUTPUT_VARIABLE actual_ninja_version
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT ninja_status EQUAL 0)
	message(FATAL_ERROR "Cannot execute Ninja: ${ninja}")
endif()
if(NOT actual_ninja_version STREQUAL locked_ninja_version)
	message(FATAL_ERROR
		"Ninja version mismatch: expected ${locked_ninja_version}, found ${actual_ninja_version}")
endif()

message(STATUS
	"Dependencies verified: LibTorch ${torch_build}, HDF5 ${locked_hdf5_version}, "
	"zlib ${locked_zlib_version}, nlohmann-json ${locked_json_version}, "
	"Ninja ${locked_ninja_version}")
